Update Test plan and fix error response in logging service
EVOLVED-5G/CAPIF_API_Services pull request #81
Opened 2023-04-03 09:15 UTC by raxonros

2023-04-03 09:27 UTC, jorgems101 requested changes

2023-04-03 09:27 UTC, jorgems101 commented on docs/test_plan/api_auditing_service/README.md
> +  1. Response to Logging Service must accomplish:
Solo indicas la respuesta del GET por lo que entiendo. No sé si es útil poner también la de la creación del log

2023-04-03 09:27 UTC, jorgems101 commented on docs/test_plan/api_auditing_service/README.md
> +  - [Test Case 1: Get a CAPIF Log Entry.](#test-case-1-creates-a-new-individual-capif-log-entry)
no hay ningún escenario de fallo posible en estas pruebas? por ejemplo que no se haya creado ninguna entrada de log, para ver que dice vacio o lo que sea neceario?

2023-04-03 09:27 UTC, jorgems101 commented on docs/test_plan/api_logging_service/README.md
> +  3. Log Entry:
entiendo que el aefId no válido es el que va en la request URI. Si es así mejor dejarlo indicado en este step con algo como {not-valid-aef-id}

2023-04-03 09:27 UTC, jorgems101 commented on docs/test_plan/api_logging_service/README.md
> +  This test case will check that a CAPIF subscriber (AEF) cannot create Log Entry without valid aefId
En este caso entiendo que es el serviceAPI no válido no el aefId, no sé si es lo mismo.

2023-04-03 09:27 UTC, jorgems101 commented on docs/test_plan/api_logging_service/README.md
> +     1. Send POST to *https://{CAPIF_HOSTNAME}/api-invocation-logs/v1/{aefId}/logs*
donde se indica ese serviceAPI no válido?

2023-04-03 09:27 UTC, jorgems101 commented on docs/test_plan/api_logging_service/README.md
> +        * detail with message "Invoker not exist".
service API no válido da como error invoker not exists?

2023-04-03 09:27 UTC, jorgems101 commented on docs/test_plan/api_logging_service/README.md
> +  This test case will check that a CAPIF subscriber (AEF) cannot create Log Entry without valid aefId
según el nombre del tests es apiinvokerId no válido, pero en la descripción se habla de un aefId no válido.

2023-04-03 09:27 UTC, jorgems101 commented on docs/test_plan/api_logging_service/README.md
> +  1. Response to Onboard request must accomplish:
se ha omitido en el resto de pruebas, porque entiendo que está en el onboard común, es relevante para este caso? hay alguna diferencia con el onboard normal?

2023-04-12 08:45 UTC, raxonros commented on docs/test_plan/api_logging_service/README.md
> +  This test case will check that a CAPIF subscriber (AEF) cannot create Log Entry without valid aefId
fixed

2023-04-12 08:49 UTC, jorgems101 approved these changes

2023-04-12 08:55 UTC, merged